### ISSUE TITLE
Error: Could not find openssl on your system on this path: openssl

### ISSUE THREAD

**Issue by batjko** [llambda/koa-boiler#6]
This error is coming from a rejected promise, right after cloning, installing and running the thing.

I assume it's because I'm on Windows, so of course there's no `openssl` executable in my path.
Do I have to install it, or should the project perhaps come with its own?

**Comment by batjko** [comment]
I've tested this and it works fine:

1. Download openssl for windows, e.g. from [here](https://indy.fulgan.com/SSL/).
2. Save the openssl executable and config files into a sub folder (e.g. `./openssl/windows`)
![image](https://user-images.githubusercontent.com/7287076/33509649-3edb5c82-d6fb-11e7-998e-abeb0602e082.png)

3. Configure pem to use those files, if we're on windows:

*server.js*
```js
;(async () => {
  // add this if statement
  if (os.platform() === 'win32') {
    process.env.OPENSSL_CONF = path.join(__dirname, 'openssl', 'windows', 'openssl.cnf')
    pem.config({
      pathOpenSSL: 'openssl.exe',
    })
  }

  // .. and that's it. Continue normally from here.
  const keys = await pem.createCertificate({
// [...]
```

**Comment by batjko** [comment]
See PR #7

**Comment by sijumonabraham** [comment]
I am getting this error. can anyone help

Calling NodeJs Library...
  Error:  Error: Could not find openssl on your system on this path: openssl
...node_modules\pem\lib\openssl.js:237:23
